name: CI python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          pip install fastapi locust pytest uvicorn coverage httpx pytest-mock pytest-profiling pylint sqlalchemy pydantic

      - name: Execute test
        run : |
          coverage run -m pytest; coverage xml

      - name: Coverage report
        uses: orgoro/coverage@v3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          coverageFile: coverage.xml
          thresholdAll: '0.8'

  release:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: major
          use_github_release_notes: true
